<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="swati3148078" name="LalaMoveChallenge.APITest.TakeOrderTest" tests="4" failures="0" timestamp="15 Nov 2018 03:54:59 GMT" time="0.007" errors="4">
  <testcase name="verifyValidResponse" time="0.002" classname="LalaMoveChallenge.APITest.TakeOrderTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at orders.PlaceOrder.getOrderId(PlaceOrder.java:48)
at baseSetup.BaseClass.getOrderCode(BaseClass.java:89)
at LalaMoveChallenge.APITest.TakeOrderTest.verifyValidResponse(TakeOrderTest.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyValidResponse -->
  <testcase name="verifyInValidOrderResponse" time="0.001" classname="LalaMoveChallenge.APITest.TakeOrderTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at orders.PlaceOrder.getOrderId(PlaceOrder.java:48)
at baseSetup.BaseClass.getOrderCode(BaseClass.java:89)
at LalaMoveChallenge.APITest.TakeOrderTest.verifyInValidOrderResponse(TakeOrderTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyInValidOrderResponse -->
  <testcase name="verifyInvalidFlowResponse" time="0.002" classname="LalaMoveChallenge.APITest.TakeOrderTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at orders.PlaceOrder.getOrderId(PlaceOrder.java:48)
at baseSetup.BaseClass.getOrderCode(BaseClass.java:89)
at LalaMoveChallenge.APITest.TakeOrderTest.verifyInvalidFlowResponse(TakeOrderTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyInvalidFlowResponse -->
  <testcase name="verifyInvalidFlowResponseMessage" time="0.002" classname="LalaMoveChallenge.APITest.TakeOrderTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at orders.PlaceOrder.getOrderId(PlaceOrder.java:48)
at baseSetup.BaseClass.getOrderCode(BaseClass.java:89)
at LalaMoveChallenge.APITest.TakeOrderTest.verifyInvalidFlowResponseMessage(TakeOrderTest.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- verifyInvalidFlowResponseMessage -->
</testsuite> <!-- LalaMoveChallenge.APITest.TakeOrderTest -->
