<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="swati3148078" name="LalaMoveChallenge.APITest.FetchOrderTest" tests="2" failures="0" timestamp="15 Nov 2018 03:54:59 GMT" time="0.036" errors="1">
  <testcase name="getValidOrderResponse" time="0.003" classname="LalaMoveChallenge.APITest.FetchOrderTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at orders.PlaceOrder.getOrderId(PlaceOrder.java:48)
at baseSetup.BaseClass.getOrderCode(BaseClass.java:89)
at LalaMoveChallenge.APITest.FetchOrderTest.getValidOrderResponse(FetchOrderTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- getValidOrderResponse -->
  <testcase name="getInValidResponse" time="0.033" classname="LalaMoveChallenge.APITest.FetchOrderTest"/>
</testsuite> <!-- LalaMoveChallenge.APITest.FetchOrderTest -->
